vich_uploader:
  db_driver: orm

  mappings:
    book_image:
      uri_prefix: /images/books
      upload_destination: '%kernel.project_dir%/public/images/books'
    user_avatar:
      uri_prefix: /images/User
      upload_destination: '%kernel.project_dir%/public/images/user'
