vich_uploader:
  db_driver: orm

  mappings:
    book_image:
      uri_prefix: /images/books
      upload_destination: '%kernel.project_dir%/public/images/books'
      namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
    blog_image:
      uri_prefix: /images/blog
      upload_destination: '%kernel.project_dir%/public/images/blog'
      namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
      delete_on_update: true
      delete_on_remove: true
    user_avatar:
      uri_prefix: /images/userAvatar
      upload_destination: '%kernel.project_dir%/public/images/userAvatar'
      namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
      delete_on_update: true
      delete_on_remove: true
